### PR TITLE
[electron, gen2] fixes RSSI failing due to Power Saving mode active [ch38428]

### LINKED ISSUE #1892: Electron 3G U270 does not report RSSI since 1.3.1-rc.1
### Expected Behavior
CellularSignal sig = Cellular.RSSI();
sig.getStrength()
sig.getQuality()
sig.getAccessTechnology()

Should report meaningful values > 0

### Observed Behavior
In some cases (possibly when connected to 2G network) 
sig.getStrength=-1
sig.getQuality=-1
sig.getAccessTechnology=0

### Steps to Reproduce
Was working fine with FW 1.2.1
Broken with 1.3.1-rc.1

Sample Code:
```
loop() {
//timer5s is increased every 5 seconds
		if (timer5s % 720 == 0) {
            snprintf(INFOchar, 620, "V: %s FW: %s FreeMem: %d Up: %ds", FWVERSION, (const char*)System.version(), System.freeMemory(), millis() / 1000);
			if (Particle.connected()) {
				CellularSignal sig = Cellular.RSSI();
                snprintf(INFOchar, 620, "V: %s FW: %s FreeMem: %d Up: %ds %.0f%%/%.0f%%/%d", FWVERSION, (const char*)System.version(), System.freeMemory(), millis() / 1000, sig.getStrength(),sig.getQuality(),sig.getAccessTechnology());
				result = Particle.publish("Info", INFOchar, 300, PRIVATE);
			}
		}
}
```
With FW 1.2.1 the results look like this:

V: e2.0.11 20190805 FW: 1.2.1 FreeMem: 70472 Up: 155137s 56%/88%/4 | 10:14 22.08.2019
V: e2.0.11 20190805 FW: 1.2.1 FreeMem: 70472 Up: 151529s 56%/88%/4 | 09:14 22.08.2019
V: e2.0.11 20190805 FW: 1.2.1 FreeMem: 70472 Up: 147924s 56%/88%/4 | 08:14 22.08.2019
V: e2.0.11 20190805 FW: 1.2.1 FreeMem: 70472 Up: 144315s 56%/88%/4 | 07:13 22.08.2019
V: e2.0.11 20190805 FW: 1.2.1 FreeMem: 70472 Up: 140709s 56%/88%/4 | 06:13 22.08.2019
V: e2.0.11 20190805 FW: 1.2.1 FreeMem: 70472 Up: 137103s 56%/88%/4 | 05:13 22.08.2019
V: e2.0.11 20190805 FW: 1.2.1 FreeMem: 70472 Up: 133496s 56%/88%/4 | 04:13 22.08.2019
V: e2.0.11 20190805 FW: 1.2.1 FreeMem: 70472 Up: 129889s 56%/88%/4 | 03:13 22.08.2019
V: e2.0.11 20190805 FW: 1.2.1 FreeMem: 70472 Up: 126282s 56%/88%/4 | 02:13 22.08.2019
V: e2.0.11 20190805 FW: 1.2.1 FreeMem: 70472 Up: 122674s 56%/88%/4 | 01:13 22.08.2019

With 1.3.1-rc.1:

V: e2.0.11 20190822 FW: 1.3.1-rc.1 FreeMem: 73072 Up: 18053s -1%/-1%/0 | 15:22 22.08.2019
V: e2.0.11 20190822 FW: 1.3.1-rc.1 FreeMem: 73088 Up: 14438s -1%/-1%/0 | 14:22 22.08.2019
V: e2.0.11 20190822 FW: 1.3.1-rc.1 FreeMem: 73088 Up: 10830s -1%/-1%/0 | 13:22 22.08.2019
V: e2.0.11 20190822 FW: 1.3.1-rc.1 FreeMem: 73088 Up: 7225s 58%/88%/4 | 12:22 22.08.2019
V: e2.0.11 20190822 FW: 1.3.1-rc.1 FreeMem: 73088 Up: 3618s 58%/88%/4 | 11:22 22.08.2019

### PR DESCRIPTION
**Pull request by technobly**
### Problem

PR #1886 added some AT / OK checks before commands with long delays, to force a quicker timeout when the AT interface was not responsive.  Unfortunately this negatively affected Gen 2 2G/3G modems due to the Power Saving mode being set to UPSV=1 by default which enables low power mode after about 9.2 seconds in most cases.  The issue is that when power saving mode is active, the AT / OK check can take longer than the 1 second timeout is currently has set, while the modem is transitioning from the IDLE to ACTIVE state.  In practice, I see this take anywhere from 0.5 seconds to 3 seconds.  The U2/G3 integration manual does not state how long this should take.

Gen 2 & Gen 3 LTE devices are not affected due to power saving mode being disabled by default.

Gen 3 2G/3G devices are also not affected due to power saving mode being disabled by default.

### Solution

If AT / OK check does not respond in 1 second, and the device is not an LTE device and does have power savings mode enabled (Gen 2 2G/3G devices), wait up to 5 seconds for the OK response and CTS line to indicate the modem is ready.

### Steps to Test

Test the example app with U260, U201, R410, and G350.  Every time getSignalStrength() is called, initial AT / OK check should succeed and not timeout before successive commands are sent.  This requires inspecting the logs.
✅ R410
✅ U201
✅ U260
✅ G350

### Device OS for this PR (use debug version)

⬇️ [particle-device-os@1.4.0+pr1917.zip](https://www.dropbox.com/s/5cxcpwapmguirc1/particle-device-os%401.4.0%2Bpr1917.zip?dl=1)

### Example App

```c
SerialLogHandler logHandler(LOG_LEVEL_ALL);
SYSTEM_MODE(SEMI_AUTOMATIC)
char myData[1024];

void setup() {    
    Particle.connect();
}

void loop() {
    if (Particle.connected()) {
        CellularSignal sig = Cellular.RSSI();
        snprintf(myData, 620, "FW: %s FreeMem: %d Up: %ds %.0f%%/%.0f%%/%d", (const char*)System.version(), System.freeMemory(), millis() / 1000, sig.getStrength(),sig.getQuality(),sig.getAccessTechnology());
        Particle.publish("Info", myData, 300, PRIVATE);
    }
    delay(20000);
}
```

### References

Fixes #1892 

---

### Completeness

- [x] User is totes amazing for contributing!
- [x] Contributor has signed CLA ([Info here](https://github.com/spark/firmware/blob/develop/CONTRIBUTING.md))
- [x] Problem and Solution clearly stated
- [x] Run unit/integration/application tests on device
- [x] N/A Added documentation
- [x] Added to CHANGELOG.md after merging (add links to docs and issues)

---

- [bugfix] [electron, gen2] fixes RSSI failing due to Power Saving mode active [#1917](https://github.com/particle-iot/device-os/pull/1917)

### CODE REVIEW

File: hal/src/electron/modem/mdm_hal.cpp [hunk 1]
```diff
@@ -335,7 +335,21 @@ int MDMParser::sendFormattedWithArgs(const char* format, va_list args) {
 bool MDMParser::_atOk(void)
 {
     sendFormated("AT\r\n");
-    return (RESP_OK == waitFinalResp(nullptr, nullptr, AT_TIMEOUT));
+    bool atok = (RESP_OK == waitFinalResp(nullptr, nullptr, AT_TIMEOUT));
```
Comment (zfields) [inline hal/src/electron/modem/mdm_hal.cpp]: I think we need to be testing for the TIMEOUT case. There are a lot of reasons it could be not `RESP_OK`, and all the remaining logic is designed to handle the case when there is specifically a timeout.

File: hal/src/electron/modem/mdm_hal.cpp [hunk 2]
```diff
@@ -335,7 +335,21 @@ int MDMParser::sendFormattedWithArgs(const char* format, va_list args) {
...
+
+    // R410 Power Savings Mode currently disabled, therefore this only affects all other modems
+    if (!atok && _dev.dev != DEV_SARA_R410 && _dev.lpm == LPM_ACTIVE) {
```
Comment (zfields) [inline hal/src/electron/modem/mdm_hal.cpp]: Instead of testing against a specific modem, perhaps we could test against a capability.

> Gen 2 & Gen 3 LTE devices are not affected due to power saving mode being disabled by default.

What if power saving mode has been enabled on these platforms, does this logic account for that situation?

Comment (technobly) [reply hal/src/electron/modem/mdm_hal.cpp]: No it does not, but we shouldn't need to add that logic until we enable power saving mode on those devices (currently it's hard coded to be disabled)

File: hal/src/electron/modem/mdm_hal.cpp (hunk 1 above)
Comment (technobly) [reply hal/src/electron/modem/mdm_hal.cpp]: It's very unlikely that it would return RESP_ERROR, RESP_ABORTED or RESP_PROMPT, but I don't mind adding an additional check to see if it is in fact the WAIT (timeout) condition.

File: hal/src/electron/modem/mdm_hal.cpp (hunk 2 above)
Comment (zfields) [reply hal/src/electron/modem/mdm_hal.cpp]: Ahh. Okay, I didn't realize it was hardcoded.

However, I do think if we don't account for it now, then we will forget it once we enable power saving mode, and have a hard to find bug at that time.

File: hal/src/electron/modem/mdm_hal.cpp (hunk 1 above)
Comment (zfields) [reply hal/src/electron/modem/mdm_hal.cpp]: That's great! When possible, I believe we should be coding for our exact intent and nothing else.

Comment (technobly) [reply hal/src/electron/modem/mdm_hal.cpp]: Added!  Decided to rebase instead of adding extra commits since there's not much code.

File: hal/src/electron/modem/mdm_hal.cpp (hunk 2 above)
Comment (technobly) [reply hal/src/electron/modem/mdm_hal.cpp]: I added TODO comments near the code that hard codes the disabling of the power modes.  Since the behavior of Power Saving mode for R410 is different than 2G/3G, it is not possible to code this logic in now without fully developing this feature for R410 (which we won't do at this time).

File: hal/src/electron/modem/mdm_hal.cpp [hunk 3]
```diff
@@ -335,7 +335,22 @@ int MDMParser::sendFormattedWithArgs(const char* format, va_list args) {
 bool MDMParser::_atOk(void)
 {
     sendFormated("AT\r\n");
-    return (RESP_OK == waitFinalResp(nullptr, nullptr, AT_TIMEOUT));
+    int resp = waitFinalResp(nullptr, nullptr, AT_TIMEOUT);
+    bool atok = (resp == RESP_OK);
+
+    // R410 Power Savings Mode currently disabled, therefore this only affects all other modems
+    if (!atok && resp == WAIT && _dev.dev != DEV_SARA_R410 && _dev.lpm == LPM_ACTIVE) {
```
Comment (zfields) [inline hal/src/electron/modem/mdm_hal.cpp]: Four conditions is intimidating. This compound `if` could benefit from removing the `!atok` check. It is redundant, because it is always true when `resp == WAIT`.

File: hal/src/electron/modem/mdm_hal.cpp (hunk 1 above)
Comment (zfields) [reply hal/src/electron/modem/mdm_hal.cpp]: I really love the simplified logic!

However, I still have an issue with checking the `_dev.dev != DEV_SARA_R410`. It looks like this logic would be covered and more importantly _ABSTRACTED_ by `_dev.lpm == LPM_ACTIVE`.

File: hal/src/electron/modem/mdm_hal.cpp (hunk 3 above)
Comment (zfields) [reply hal/src/electron/modem/mdm_hal.cpp]: I really love the simplified logic!

However, I still have an issue with checking the _dev.dev != DEV_SARA_R410. It looks like this logic would be covered, and more importantly ABSTRACTED, by _dev.lpm == LPM_ACTIVE.
