### PR TITLE
[Gen 3] Fix retained values not initializing correctly [ch42294]

### LINKED ISSUE #1919: [Gen 3] retained int value is not initialized
<details>
  <summary><i>retained int returns wrong value on first use and after system reset</i></summary>

</details>

### Expected Behavior

Serial output:
Starting retained var test
savedValue=0
savedValue=1
savedValue=2
savedValue=3
savedValue=4

etc...

### Observed Behavior

Serial output:
Starting retained var test
savedValue=-778261199
savedValue=-778261198
savedValue=-778261197
savedValue=-778261196
savedValue=-778261195
savedValue=-778261194
savedValue=-778261193
savedValue=-778261192
savedValue=-778261191

### Steps to Reproduce

Firmware 1.4.0 (also confirmed on 1.4.2)
flash Test app
Device is a standalone argon with no battery

### Test App

```

STARTUP(System.enableFeature(FEATURE_RETAINED_MEMORY)); 
retained int savedValue = 0; 

void setup() {
    Serial.begin(115200);
    
    while (!Serial.isConnected())
    Particle.process();
    Serial.printf(
      "\nStarting retained var test");
} 

void loop() { 
    Serial.printlnf("savedValue=%d", savedValue++); 
    delay(1000);
}

```

### References

https://community.particle.io/t/retained-memory-tips/38137
https://community.particle.io/t/retained-memory-not-working-correctly/46869
https://community.particle.io/t/retained-memory-support-on-gen-3-devices/50512/5

---

## Feature/Enhancement Request

retain an int value for use between soft restarts

### PR DESCRIPTION
**Pull request by keeramis**
<details>
  <summary><i>submission notes</i></summary>

```
**Important:** Please sanitize/remove any confidential info like usernames, passwords, org names, product names/ids, access tokens, client ids/secrets, or anything else you don't wish to share.

Please Read and Sign the Contributor License Agreement ([Info here](https://github.com/spark/firmware/blob/develop/CONTRIBUTING.md)).

You may also delete this submission notes header if you'd like. Thank you for contributing!
```
</details>

### Problem

Variables that are defined as "retained" which are supposed to retain the value of variable across system reboots are not getting initialized correctly as expected, on Gen3. 

### Solution

Added a new feature flag HAL_PLATFORM_BACKUP_RAM, that fixes bad initialization values for both Gen2 and Gen3

### Steps to Test

Test a "retained" variable that gets initialized as expected, as per the value you set.

### Example App

```c
#include "application.h"
STARTUP(System.enableFeature(FEATURE_RETAINED_MEMORY));
retained int retain_var = 0;

Serial1LogHandler logHandler(115200, LOG_LEVEL_ALL);
void setup() {
  retain_var++;
  Log.info("retain_var within retains: %d", retain_var);
}

void loop() {}
```

### References

https://app.clubhouse.io/particle/story/42294/gen-3-retained-int-value-is-not-initialized
Closes #1919 

---

### Completeness

- [x] User is totes amazing for contributing!
- [x] Contributor has signed CLA ([Info here](https://github.com/spark/firmware/blob/develop/CONTRIBUTING.md))
- [x] Problem and Solution clearly stated
- [x] Run unit/integration/application tests on device
- [ ] Added documentation
- [ ] Added to CHANGELOG.md after merging (add links to docs and issues)

### CODE REVIEW

File: wiring/src/user.cpp [hunk 1]
```diff
@@ -128,7 +128,7 @@ void serialEventRun()
 #endif
 }
 
-#if defined(STM32F2XX)
+#if defined(HAL_PLATFORM_BACKUP_RAM)
 #define PLATFORM_BACKUP_RAM 1
```
Comment (avtolstoy) [inline wiring/src/user.cpp]: Nit: ideally, we'd remove this if/else and define altogether and just use `HAL_PLATFORM_BACKUP_RAM` everywhere in place of `PLATFORM_BACKUP_RAM`.

File: hal/inc/hal_platform_compat.h [hunk 2]
```diff
@@ -87,4 +87,6 @@
 #define HAL_PLATFORM_NETWORK_MULTICAST (1)
 #endif // HAL_PLATFORM_WIFI
 
+#define HAL_PLATFORM_BACKUP_RAM (1)
```
Comment (avtolstoy) [inline hal/inc/hal_platform_compat.h]: Core build seems to be broken. We are anyway removing it, but let's for now move this define above under `PLATFORM_ID >= PLATFORM_PHOTON_PRODUCTION && PLATFORM_ID != PLATFORM_NEWHAL` check.
