### PR TITLE
Backport fixes for 1.2.1-rc.3

### LINKED ISSUE #1811: 1.2.1-rc.2 regression: Only three of four Particle.subscribe handlers get registered
With this simple test code only the handlers t1..t3 get called t4 doesn't do anything.
```
void setup() {
  Serial.begin();
  Particle.subscribe("t1", test, MY_DEVICES);
  Particle.subscribe("t2", test, MY_DEVICES);
  Particle.subscribe("t3", test, MY_DEVICES);
  Particle.subscribe("t4", test, MY_DEVICES);
}

void test(const char* event, const char* data) {
  Serial.println(event);
}
```
This works as expected (t1..t4) with 1.1.0 but 1.2.1-rc.2 fails (not tried intermediate RCs)
Tested with Photon and Argon.

### PR DESCRIPTION
**Pull request by technobly**
## This PR consists of fixes and enhancements cherry-picked from develop to create 1.2.1-rc.3

- [bugfix] [lte] cellular fixes [#1824](https://github.com/particle-iot/device-os/pull/1824)
- [bugfix] fixes #1811 - increases the number of event handlers to 6 [#1822](https://github.com/particle-iot/device-os/pull/1822)
- [bugfix] [gen 3] fixes memory usage diagnostics (reported negative values in safe mode) [#1819](https://github.com/particle-iot/device-os/pull/1819)
- [bugfix] System.disableUpdates() operates asynchronously [#1801](https://github.com/particle-iot/device-os/pull/1801)
- [enhancement] allow the bootloader to be flashed over DFU [#1788](https://github.com/particle-iot/device-os/pull/1788)

### CODE REVIEW

File: communication/tests/catch/protocol.cpp [hunk 1]
```diff
@@ -66,11 +66,11 @@ void event_handler(const char* event, const char* data)
 {
 }
 
-SCENARIO("5 subscribe messages are registered")
+SCENARIO("6 subscribe messages are registered")
```
Comment (zfields) [inline communication/tests/catch/protocol.cpp]: Shouldn't you use MAX_SUBSCRIPTIONS here and in the test as well?

Comment (technobly) [reply communication/tests/catch/protocol.cpp]: Yes probably :)  We'll have to fix it going forward.

Comment (technobly) [reply communication/tests/catch/protocol.cpp]: Might be hard to include protocol_defs.h though... not sure.  At least if the number changes the test will fail.  That said, this test was/is broken and fixed in PR https://github.com/particle-iot/device-os/pull/1524 so we need to get that fixed up and merged asap.
