### PR TITLE
[wiring] Make sure that `Serial` and `SerialX` methods are in sync with the documentation and don't return unexpected values

### LINKED ISSUE #1737: [Gen3] USARTSerial::read() returns -260 instead of -1 for empty RX buffer
Unlinke the [documentation](https://docs.particle.io/reference/device-os/firmware/xenon/#read-) states 
image

and also in contradiction to the known behaviour of Gen1 & Gen2 devices Gen3 returns -260 instead of -1

Tested with 0.9.0

### PR DESCRIPTION
**Pull request by avtolstoy**
### Problem

#1737

### Solution

Make sure that `available()`, `availableForWrite()`, `peek()` and `read()` don't forward the errors from HAL and only return 0 or -1 in case of errors appropriately.

### Steps to Test

N/A

### Example App

N/A

### References

- Closes #1737
- [CH32372]

---

### Completeness

- [x] User is totes amazing for contributing!
- [x] Contributor has signed CLA ([Info here](https://github.com/spark/firmware/blob/develop/CONTRIBUTING.md))
- [x] Problem and Solution clearly stated
- [x] Run unit/integration/application tests on device
- [ ] Added documentation
- [ ] Added to CHANGELOG.md after merging (add links to docs and issues)

---

- [wiring] Make sure that `Serial` and `SerialX` methods are in sync with the documentation and don't return unexpected values [#1782](https://github.com/particle-iot/device-os/pull/1782)

### CODE REVIEW

**Comment by m-mcgowan** [comment]
I'm not sure about this - rather than breaking the . behaviour wouldn't;'t it be better to instead update the documentation? That way we make no breaking changes to existing apps.

**Comment by avtolstoy** [comment]
We are not really breaking the behavior, but restoring it here at the very least for Gen 3? :smile: Currently `Serial1.read()` may return `-260` on Gen 3 (`SYSTEM_ERROR_NO_MEMORY`, which is actually somewhat wrong), and I assume many apps simply check for `!= -1` instead of `< 0` for error conditions.

We've discussed this previously and came to a conclusion that as a first step we'd ensure that no error codes are propagating up to the wiring caller and we are in conformance with the documentation and then later would change the behavior, documentation as well as notify about the breaking change in the release notes. I agree though that with 1.2.0 we may go straight to doing that. So, what do we do?

File: wiring/src/spark_wiring_usbserial.cpp [hunk 1]
```diff
@@ -99,7 +98,7 @@ void USBSerial::blockOnOverrun(bool block)
 
 int USBSerial::peek()
 {
-	return HAL_USB_USART_Receive_Data(_serial, true);
+	return std::max(0, (int)HAL_USB_USART_Receive_Data(_serial, true));
```
Comment (sergeuz) [inline wiring/src/spark_wiring_usbserial.cpp]: This should be `std::max(-1, ...)`
